"""
convert_to_tflite.py
--------------------
Converts the trained Keras model to INT8 TFLite and
exports emotion_model.h for the ESP32 firmware.

Usage:
    python convert_to_tflite.py
    python convert_to_tflite.py --model emotion_model_best.keras --data_dir ../data
"""

import os
import argparse
import numpy as np
import tensorflow as tf
from tensorflow import keras

IMG_SIZE = 48
CLASS_MAP = {
    "happy":    0,
    "neutral":  1,
    "surprise": 1,
    "angry":    2,
    "disgust":  2,
    "fear":     2,
    "sad":      3,
}
LABEL_NAMES = ["Happy", "Neutral", "Stressed", "Sad"]


def load_rep_samples(data_dir, n=400):
    images = []
    train_dir = os.path.join(data_dir, "train")
    folders = [f for f in os.listdir(train_dir)
               if os.path.isdir(os.path.join(train_dir, f))
               and f.lower() in CLASS_MAP]

    per_class = max(1, n // len(folders))
    for folder in folders:
        folder_path = os.path.join(train_dir, folder)
        files = [f for f in os.listdir(folder_path)
                 if f.lower().endswith((".png", ".jpg", ".jpeg"))]
        np.random.shuffle(files)
        for fname in files[:per_class]:
            try:
                img = keras.utils.load_img(
                    os.path.join(folder_path, fname),
                    color_mode="grayscale",
                    target_size=(IMG_SIZE, IMG_SIZE),
                )
                arr = keras.utils.img_to_array(img).astype(np.float32) / 255.0
                images.append(arr)
            except Exception:
                pass

    np.random.shuffle(images)
    return images[:n]


def write_c_header(model_bytes: bytes, path: str):
    var = "emotion_model_tflite"
    num_classes = 4
    lines = [
        "// Auto-generated by convert_to_tflite.py — do not edit manually.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"// Classes: Happy(0)  Neutral(1)  Stressed(2)  Sad(3)",
        f"// Model size: {len(model_bytes)} bytes  ({len(model_bytes)/1024:.1f} KB)",
        f"#define NUM_CLASSES {num_classes}",
        f'const char* const LABEL_NAMES[{num_classes}] = {{"Happy", "Neutral", "Stressed", "Sad"}};',
        f'const char* const LABEL_ICONS[{num_classes}] = {{":)", ":|", ":(", ":C"}};',
        "",
        f"alignas(8) const uint8_t {var}[] = {{",
    ]
    hex_vals = [f"0x{b:02x}" for b in model_bytes]
    for i in range(0, len(hex_vals), 12):
        lines.append("  " + ", ".join(hex_vals[i:i+12]) + ",")
    lines += [
        "};",
        f"const unsigned int {var}_len = {len(model_bytes)};",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def convert(args):
    np.random.seed(42)
    print(f"Loading: {args.model}")
    model = tf.keras.models.load_model(args.model)

    print(f"Loading {args.n_rep} representative samples for calibration...")
    rep_images = load_rep_samples(args.data_dir, n=args.n_rep)
    print(f"  Got {len(rep_images)} samples")

    def representative_dataset():
        for img in rep_images:
            yield [np.expand_dims(img, axis=0)]

    # Full INT8 quantization
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    print("Converting...")
    tflite_model = converter.convert()
    size_kb = len(tflite_model) / 1024
    print(f"Model size: {size_kb:.1f} KB")

    if size_kb > 250:
        print("WARNING: Model may be too large. Consider reducing architecture.")
    elif size_kb > 150:
        print("NOTE: Larger than ideal but will fit in ESP32 PSRAM.")
    else:
        print("Size OK for ESP32 deployment.")

    # Save .tflite
    with open("emotion_model.tflite", "wb") as f:
        f.write(tflite_model)
    print("Saved: emotion_model.tflite")

    # Verify
    interp = tf.lite.Interpreter(model_content=tflite_model)
    interp.allocate_tensors()
    inp_d  = interp.get_input_details()[0]
    out_d  = interp.get_output_details()[0]
    print(f"Input:  shape={inp_d['shape']}  dtype={inp_d['dtype']}")
    print(f"Output: shape={out_d['shape']}  dtype={out_d['dtype']}")

    # Sanity run
    dummy = np.zeros((1, IMG_SIZE, IMG_SIZE, 1), dtype=np.int8)
    interp.set_tensor(inp_d["index"], dummy)
    interp.invoke()
    out = interp.get_tensor(out_d["index"])
    print(f"Sanity output: {out}")

    # Generate C header
    write_c_header(tflite_model, "emotion_model.h")
    print("Saved: emotion_model.h")
    print("\nNext step: copy emotion_model.h into firmware/EdgeWatch/")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model",    default="emotion_model_best.keras")
    parser.add_argument("--data_dir", default="../data")
    parser.add_argument("--n_rep",    type=int, default=400,
                        help="Number of representative samples for INT8 calibration")
    args = parser.parse_args()
    convert(args)
