"""
EdgeGaze — TFLite Conversion + C Header Generator
Run: python convert_tflite.py

Converts emotion_model.h5 → INT8 quantized .tflite → model.h (C array)
Then copies model.h into ../firmware/
"""

import os
import sys
import subprocess
import numpy as np

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import tensorflow as tf

# ── Config ───────────────────────────────────────────────────────────────────
CLASSES      = ["happy", "angry", "sad", "neutral"]
IMG_SIZE     = 48
MODEL_H5     = "emotion_model.h5"
TFLITE_PATH  = "emotion_model.tflite"
HEADER_PATH  = "../firmware/model.h"
DATA_DIR     = "data"
CAL_SAMPLES  = 200   # representative samples for calibration


# ── Load calibration data ────────────────────────────────────────────────────
def load_calibration_data():
    images = []
    for label in CLASSES:
        folder = os.path.join(DATA_DIR, label)
        if not os.path.exists(folder):
            continue
        files = [f for f in os.listdir(folder) if f.endswith(".jpg")][:CAL_SAMPLES // len(CLASSES)]
        for fname in files:
            img = tf.keras.preprocessing.image.load_img(
                os.path.join(folder, fname),
                color_mode="grayscale",
                target_size=(IMG_SIZE, IMG_SIZE),
            )
            arr = tf.keras.preprocessing.image.img_to_array(img) / 255.0
            images.append(arr)
    return np.array(images, dtype="float32")


def representative_dataset_gen(cal_data):
    def gen():
        for img in cal_data:
            yield [img[np.newaxis, :, :, :]]
    return gen


# ── Convert ──────────────────────────────────────────────────────────────────
def convert():
    if not os.path.exists(MODEL_H5):
        print(f"[ERROR] {MODEL_H5} not found. Run train.py first.")
        sys.exit(1)

    print(f"[1/4] Loading {MODEL_H5}...")
    model = tf.keras.models.load_model(MODEL_H5)
    print(f"  Parameters: {model.count_params():,}")

    print("\n[2/4] Loading calibration data...")
    cal_data = load_calibration_data()
    print(f"  Calibration samples: {len(cal_data)}")

    print("\n[3/4] Converting to TFLite INT8...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen(cal_data)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    with open(TFLITE_PATH, "wb") as f:
        f.write(tflite_model)

    size_kb = len(tflite_model) / 1024
    print(f"  Saved {TFLITE_PATH} ({size_kb:.1f} KB)")

    if size_kb > 300:
        print("  [WARN] Model >300KB — may be tight for ESP32 SRAM. Consider reducing layer sizes.")

    # ── Verify quantized model ────────────────────────────────────────────────
    print("\n  Verifying quantized model...")
    interp = tf.lite.Interpreter(model_path=TFLITE_PATH)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    print(f"  Input  dtype: {inp['dtype']}, shape: {inp['shape']}")
    print(f"  Output dtype: {out['dtype']}, shape: {out['shape']}")

    # Quick accuracy check on first 50 val samples
    correct = 0
    total   = min(50, len(cal_data))
    for img in cal_data[:total]:
        scale, zp = inp["quantization"]
        quantized  = (img[np.newaxis] / scale + zp).astype(np.int8)
        interp.set_tensor(inp["index"], quantized)
        interp.invoke()
        result = interp.get_tensor(out["index"])
        if np.argmax(result) == 0:   # just checking it runs cleanly
            pass
        correct += 1
    print(f"  Inference runs clean on {correct}/{total} samples ✓")

    # ── Generate C header ─────────────────────────────────────────────────────
    print(f"\n[4/4] Generating C header → {HEADER_PATH}...")

    hex_bytes = ", ".join(f"0x{b:02x}" for b in tflite_model)
    n = len(tflite_model)

    header = f"""// Auto-generated by EdgeGaze convert_tflite.py
// Model: {TFLITE_PATH}  |  Size: {size_kb:.1f} KB  |  Quantization: INT8
// DO NOT EDIT MANUALLY

#ifndef EDGEGAZE_MODEL_H
#define EDGEGAZE_MODEL_H

#include <stdint.h>

// Input scale/zero_point from TFLite metadata
// Input  : INT8, shape [1, 48, 48, 1]
// Output : INT8, shape [1, 4]   (happy=0, angry=1, sad=2, neutral=3)

const unsigned int   g_model_len  = {n};
const unsigned char  g_model_data[] = {{
  {hex_bytes}
}};

#endif  // EDGEGAZE_MODEL_H
"""

    os.makedirs(os.path.dirname(HEADER_PATH), exist_ok=True)
    with open(HEADER_PATH, "w") as f:
        f.write(header)

    print(f"  Written {HEADER_PATH}  ({n:,} bytes)")
    print(f"\n  Done! Flash firmware/ with Arduino IDE next.\n")

    print("=" * 50)
    print("  SUMMARY")
    print("=" * 50)
    print(f"  .h5 (float32) : {os.path.getsize(MODEL_H5) / 1024:.1f} KB")
    print(f"  .tflite INT8  : {size_kb:.1f} KB")
    print(f"  Compression   : {os.path.getsize(MODEL_H5) / len(tflite_model):.1f}x")
    print(f"  C header      : {HEADER_PATH}")
    print("=" * 50)


if __name__ == "__main__":
    convert()